version: '3'
services:
  vpn_proxy:
    image: jolt/ovpn-openvpn-privoxy
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - 208.67.220.220
      - 208.67.222.222
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - REGION=se
      - USERNAME=${OVPN_USERNAME}
      - PASSWORD=${OVPN_PASSWORD}
      - LOCAL_NETWORK=172.16.0.0/20
    networks:
      - ovpn-openvpn-privoxy
    ports:
      - 8118:8118
    restart: always

networks:
  vpn_proxy:
